# Regression

## Types of regression Models.
- Simple Regression.
- - Simple Linear Regression (y = f(x) = ax + b)
  - Simple Non-Linear Regression. (Any other equation apart from ax+b is non-linear). 
- Multiple Regression.
- - Multiple Linear Regression.
  - Multiple Non-linear Regression.
 
## Applications of regression. 
- Sales forecasting.
- Satisfaction analysis.
- Price estimation.
- Employment income.

## 1. Simple Linear Rgression: Intuition.
- In simple linear regression, wepredict the value of one variable Y based on another variable X.
- X is called teh independent variable and Y is callled the dependant variable.
- Why simple? Because it examines relationship between two variables only.
- Why linear? when the independent variable increases (or deceases), the dependent variable increases(or decreases) in a linear fashion.

## Simple Linear Regression: How to obtain model parameters? Least Sum of Squares. 
- Least square fitting is a way to find the best fit curve or line for a set of points.
- The sum of the squares of the offsets(residuals) are used to estimate the best fit curve or line.
- Least squares method is used to obtain the coefficients m and b.

## Examples

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"X":[1,2,3,4,5],"Y":[6,7,5,5,10]})

In [3]:
df

X   Y
0  1   6
1  2   7
2  3   5
3  4   5
4  5  10

In [5]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(df[["X"]],df["Y"])

#model.fit will pridect best equation (also callled as mode) mx +c 

LinearRegression()

In [16]:
#this is m part of y = mx + c equation. 
model.intercept_

4.8

In [15]:
#This is the c part of the equation. 
model.coef_

array([0.6])

In [8]:
ypred = model.predict(df[["X"]])
ypred

array([5.4, 6. , 6.6, 7.2, 7.8])

In [9]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(df["Y"],ypred)
mse

2.7199999999999998

In [11]:
import numpy as np
np.sqrt(mse)

1.649242250247064

In [13]:
model.score(df[["X"]],df["Y"])

0.2093023255813954

In [14]:
model.predict([[6]])

/Users/puli/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.4])

# ------------------------

# Steps involded in simple linear regression. 

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"X":[1,2,3,4,5],"Y":[6,7,8,9,10]})

df

X   Y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

###  --Modeling--

In [12]:
#Step 1: Split the data into test and train. 
x = df[["X"]]
y = df["Y"]

In [13]:
x

X
0  1
1  2
2  3
3  4
4  5

In [14]:
y

0     6
1     7
2     8
3     9
4    10
Name: Y, dtype: int64

In [23]:
#train_test_split is the function from sklearn that we need to use to split the data into train and test. 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

x_train

X
2  3
0  1
1  2
3  4

In [24]:
x_test

X
4  5

In [25]:
y_train

2    8
0    6
1    7
3    9
Name: Y, dtype: int64

In [26]:
y_test

4    10
Name: Y, dtype: int64

In [27]:
#Step 2: Apply Al on train data to find the equation (fit the model)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(x_train,y_train)

LinearRegression()

In [28]:
model.coef_

array([1.])

In [29]:
model.intercept_

5.0

###  --Prediction--

In [34]:
#Step 3: predect the ypred_train on train data. 

ypred_train = model.predict(x_train)

ypred_train

array([8., 6., 7., 9.])

In [35]:
#Step 4: predect the ypred_test on test data. 

ypred_test = model.predict(x_test)

ypred_test

array([10.])

###  --Evaluation--

In [41]:
#Step 5:: Calculate R2_test, R2_train

Rsqr_train = model.score(x_train,y_train)

print(Rsqr_train)

Rsqr_train = model.score(x_test,y_test)

print(Rsqr_train)  # this will through error because 0/0 usually this will not happen but our data set is small. 

1.0
nan


/Users/puli/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_regression.py:796: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


###  --Modeal Selection--

Following three condition SHOULD BE satisifed to say the model is good or bad.
- Train Accuracy = Test Accuracy (+- 5%)
- Cross Validation Score = Test Accuracy.
- Client Requirement (Example:: If client ask for 85% accurate model). 

# Regularization
- Regularization seeks to solve a few common model issues by:
- - Minimizing model complexity.
  - Penalizing the loos function (Penalizing error). 
  - Reducing model overfitting (add more bias to reduce model variance).
- as a way to reduce model overfitting and variance.
- - Requires some additional bias
  - Requires a search for optimal penalty hyperparameter.
 
## Three main type of Regularization. 
- L1 Regularization.
- - LASSO Regression.
- L2 Regularization.
- - Ridge Regression.
- Combining L1 and L2
- - Elastic Net.