# NumPy
- NumPy (Numerical Python) is an open source Python library that aids in nathematical and scientific programming.
- - Used for working with arrays.
  - In python we have lists that serve the purpose of arrays, but they are slow to process.
  - NumPy aims to provide an array object that is up to 50x faster than the aditional python lists.
  - NumPy is incradible library to perform mathematical and statistical operations due to it's fast and memory efficient.
  - So processes can access and manipulate them very efficiently. Also it is optimized to work with latest CPU architectures.
  - designed for working in domain of linear algebra, fourier transformations, matrices.
  - NumPy works only with lists. 

In [9]:
a = [1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
## Import NumPy
import numpy as np

In [ ]:
np.__version__
## os is used to know the version of NumPy module. 

In [12]:
a = [1,2,3,4,5]
np_a = np.array(a)  # This is create an array. 
print(np_a)
print(type(np_a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
##-----------------------------------##

In [14]:
# Without NumPy. 

# Add the elements of two arrayrs. 

l1 = [1,2,3]
l2 = [4,3,2]

# l1 + l2 = l3 = [5,5,5]   desired output. 

l3 = []
for i in range(0,3):
    a = l1[i] + l2[i]
    l3.append(a)
print(l3)

[5, 5, 5]


In [15]:
# same with NumPy.

import numpy as np

l1 = [1,2,3]
l2 = [4,3,2]

np_l1 = np.array(l1)
np_l2 = np.array(l2)

l3 = np_l1 + np_l2

print(l3)

[5 5 5]


## Creating NumPy Arrays From a List. 

In [16]:
# 0-D  - Zero Dimension Array. 

arr = np.array(42)
print(arr)
type(arr)

42


numpy.ndarray

In [17]:
# 1-D - One Dimensional Array
import numpy as np

a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [18]:
# Print the dimensions of an arrary. 
a.ndim

1

In [19]:
#shape
a.shape

(4,)

In [20]:
 # 2-D - Two Dimensional Array. 

b = np.array([[0,1,2], [3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [21]:
b.ndim

2

In [24]:
b.shape  # in this there are two row and 3 columns.

(3, 3)

In [23]:
#Matrix

my_matric = [[1,2,3],[4,5,6],[7,8,9]]

b = np.array(my_matric)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
b.ndim

2

In [26]:
b.shape

(3, 3)

## Functions to creating arrays. 

### arange
- arange is an array-valued version of the built-in Python range function.
- Syntax: np.arange(start,end,step)

In [27]:
a = np.arange(10,100,10) # start, end(exclusive),step
print(a)

[10 20 30 40 50 60 70 80 90]


In [28]:
a.ndim

1

In [29]:
a.shape

(9,)

### linespace
- Return evenly spaced numbers over a specified interval.
- Syntax: np.linspace(start, end, num_of_samples)
- Default num_of_samples is 50 (you can find this in help file (shit+tab))

In [30]:
ls = np.linspace(0, 10, 3)
print(ls)

[ 0.  5. 10.]


In [31]:
ls.shape

(3,)

In [32]:
ls = np.linspace(0,100,101)
ls

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

### zeros
- Generate arrays of zeros.
- Syntax: np.zeros(shape)

In [33]:
np.zeros((3,),dtype=int)

array([0, 0, 0])

In [34]:
np.zeros((3,3)) # Zero matrix or null matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### random.randint
- Return random integers from start(inclusive) to end (exclusive)
- Syntax: np.random.randint(start,end,num_of_samples)

In [35]:
np.random.randint(1,10,5)

array([4, 6, 8, 9, 4])

# Accesing elements
- Accessing a single value through indexing.
- Accessing a multiple value based on indexing.
- Accessing a multiple value based on indexing.
- Accessing a multiple value based on condition. 

### Indexing
- indexing a single value.

In [36]:
a = np.arange(0,31,3)
print(a)
print("Index:",a[5])

[ 0  3  6  9 12 15 18 21 24 27 30]
Index: 15


### Slicing

In [37]:
a[1:8:2] #[startingdex: endindex(exclusive):step}

array([ 3,  9, 15, 21])

### Indexing multiple values Indexing.
syntax: array[list of index numbers]

In [38]:
#Indexing can be done with an array of integers, where the same index is represented.
a[[0,3,4,5,10]]

array([ 0,  9, 12, 15, 30])

### Mask Indexing or Fancy Indexing (Important topic)

In [39]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [41]:
a[a%2==0]   # only true values are take. 

array([ 0,  6, 12, 18, 24, 30])

## Numpy is Mutable (Replace, Add, Remove)

### Replacing a singel value in a array

In [42]:
a[3] = 50
print(a)

[ 0  3  6 50 12 15 18 21 24 27 30]


### Replacing multiple values in a array. 

In [43]:
a[[2,3]] = 40
a

array([ 0,  3, 40, 40, 12, 15, 18, 21, 24, 27, 30])

### Add values in a array

In [45]:
a = np.array([4,7,8])
a = np.append(a,[2,4,5])
print("Numpy array after addition:",a)

Numpy array after addition: [4 7 8 2 4 5]


### Delete a single value in a array

In [47]:
a = np.delete(a,4)
print("Numpy array after deletion of one element:",a)

Numpy array after deletion of one element: [4 7 8 2 5]


### Delete a multiple values in a array

In [48]:
a = np.delete(a,[1,2])
a

array([4, 2, 5])

### Sort

In [50]:
np.sort([4,5,8,2,20])

array([ 2,  4,  5,  8, 20])

### Copy array

In [51]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Operations
### Flattening
    - - Converting n-D array to 1-D array


In [52]:
a = np.array([[1,2,3], [4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

### Reshape array

In [53]:
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [54]:
# Notice the two sets of brackets.
a1 = arr.reshape(2,10)
a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [55]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


### Transpose array

In [57]:
print(a)
c = a.T
print(c)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### Sort

In [58]:
#Sorting along an axis: axis=1 --> row and axis =0 --> column
a = np.array([[5,4,6], [2,8,3]])
b = np.sort(a,axis=0)
b

array([[2, 4, 3],
       [5, 8, 6]])

In [59]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [63]:
print(a[1,1])   # index aij   where i = row, j=column 

2


In [64]:
a[1,1] = 35 # assigning values
a

array([[ 1,  0,  0],
       [ 0, 35,  0],
       [ 0,  0,  3]])

## Arthimetic Operations. 

In [65]:
a = np.array([1,2,3,4]) # create an array. 
print(a)

[1 2 3 4]


In [66]:
print(a+1)

[2 3 4 5]


In [67]:
a ** 2

array([ 1,  4,  9, 16])

In [72]:
b = np.ones((4,)) + 1
b

array([2., 2., 2., 2.])

In [73]:
a + b

array([3., 4., 5., 6.])

In [75]:
a - b

array([-1.,  0.,  1.,  2.])

In [77]:
a * b

array([2., 4., 6., 8.])

In [83]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,4],[4,4]])

#adding a and b element-wise addition. 
print(a+b)

[[5 6]
 [7 8]]


In [84]:
print(a*b)  #Element-wise multiplication. 

[[ 4  8]
 [12 16]]


In [85]:
# Acutal matrix multiplications. 
np.matmul(a,b)

array([[12, 12],
       [28, 28]])

## Comparision operations. 

In [86]:
a = np.array([1,2,3,4])
b = np.array([5,5,5,4])
a == b

array([False, False, False,  True])

In [87]:
a > b

array([False, False, False, False])

In [88]:
#array-wise comparisions.
a = np.array([1,2,3,4])
b = np.array([5,5,5,4])
c = np.array([1,2,3,4])

In [89]:
np.array_equal(a,b)

False

In [90]:
np.array_equal(a,c)

True

## Mathamatic operations. 

In [94]:
import numpy as np

a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [95]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [96]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [97]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])