# NumPy
- NumPy (Numerical Python) is an open source Python library that aids in nathematical and scientific programming.
- - Used for working with arrays.
  - In python we have lists that serve the purpose of arrays, but they are slow to process.
  - NumPy aims to provide an array object that is up to 50x faster than the aditional python lists.
  - NumPy is incradible library to perform mathematical and statistical operations due to it's fast and memory efficient.
  - So processes can access and manipulate them very efficiently. Also it is optimized to work with latest CPU architectures.
  - designed for working in domain of linear algebra, fourier transformations, matrices.
  - NumPy works only with lists. 

In [3]:
a = [1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
## Import NumPy
import numpy as np

In [6]:
np.__version__
## os is used to know the version of NumPy module. 

'1.21.5'

In [7]:
a = [1,2,3,4,5]
np_a = np.array(a)  # This is create an array. 
print(np_a)
print(type(np_a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
##-----------------------------------##

In [1]:
# Without NumPy. 

# Add the elements of two arrayrs. 

l1 = [1,2,3]
l2 = [4,3,2]

# l1 + l2 = l3 = [5,5,5]   desired output. 

l3 = []
for i in range(0,3):
    a = l1[i] + l2[i]
    l3.append(a)
print(l3)

[5, 5, 5]


In [11]:
# same with NumPy.

import numpy as np

l1 = [1,2,3]
l2 = [4,3,2]

np_l1 = np.array(l1)
np_l2 = np.array(l2)

l3 = np_l1 + np_l2

print(l3)

[5 5 5]


## Creating NumPy Arrays From a List. 

In [17]:
# 0-D  - Zero Dimension Array. 

arr = np.array(42)
print(arr)
type(arr)

42


numpy.ndarray

In [16]:
# 1-D - One Dimensional Array
import numpy as np

a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [18]:
# Print the dimensions of an arrary. 
a.ndim

1

In [22]:
#shape
a.shape

(4,)

In [24]:
 # 2-D - Two Dimensional Array. 

b = np.array([[0,1,2], [3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [26]:
b.ndim

2

In [28]:
b.shape  # in this there are two row and 3 columns.

(2, 3)

In [32]:
#Matrix

my_matric = [[1,2,3],[4,5,6],[7,8,9]]

b = np.array(my_matric)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
b.ndim

2

In [34]:
b.shape

(3, 3)

## Functions to creating arrays. 

### arange
- arange is an array-valued version of the built-in Python range function.
- Syntax: np.arange(start,end,step)

In [35]:
a = np.arange(10,100,10) # start, end(exclusive),step
print(a)

[10 20 30 40 50 60 70 80 90]


In [37]:
a.ndim

1

In [38]:
a.shape

(9,)

### linespace
- Return evenly spaced numbers over a specified interval.
- Syntax: np.linspace(start, end, num_of_samples)
- Default num_of_samples is 50 (you can find this in help file (shit+tab))

In [45]:
ls = np.linspace(0, 10, 3)
print(ls)

[ 0.  5. 10.]


In [46]:
ls.shape

(3,)

In [50]:
ls = np.linspace(0,100,101)
ls

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

### zeros
- Generate arrays of zeros.
- Syntax: np.zeros(shape)

In [54]:
np.zeros((3,),dtype=int)

array([0, 0, 0])

In [53]:
np.zeros((3,3)) # Zero matrix or null matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### random.randint
- Return random integers from start(inclusive) to end (exclusive)
- Syntax: np.random.randint(start,end,num_of_samples)

In [55]:
np.random.randint(1,10,5)

array([6, 7, 2, 2, 7])

# Accesing elements
- Accessing a single value through indexing.
- Accessing a multiple value based on indexing.
- Accessing a multiple value based on indexing.
- Accessing a multiple value based on condition. 

### Indexing
- indexing a single value.

In [59]:
a = np.arange(0,31,3)
print(a)
print("Index:",a[5])

[ 0  3  6  9 12 15 18 21 24 27 30]
Index: 15


### Slicing

In [60]:
a[1:8:2] #[startingdex: endindex(exclusive):step}

array([ 3,  9, 15, 21])

### Indexing multiple values Indexing.
syntax: array[list of index numbers]

In [62]:
#Indexing can be done with an array of integers, where the same index is represented.
a[[0,3,4,5,10]]

array([ 0,  9, 12, 15, 30])

### Mask Indexing or Fancy Indexing (Important topic)

In [63]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [65]:
a[a%2==0]   # only true values are take. 

array([ 0,  6, 12, 18, 24, 30])